import type {
  Customer,
  DashboardStats,
  Employee,
  Invoice,
  Payment,
  Quote,
  ScheduleEvent,
} from "@/types";
import { getEmployeeFullName } from "@/lib/employee-utils";

export const dashboardStats: DashboardStats = {
  totalRevenue: 487250,
  pendingInvoices: 12,
  activeProjects: 8,
  totalCustomers: 47,
  upcomingJobs: 5,
  employeesOnSite: 14,
};

export const customers: Customer[] = [
  {
    id: "cust-1",
    name: "Sarah Mitchell",
    email: "sarah@mitchellproperties.com",
    phone: "(555) 234-5678",
    address: "1420 Oak Street, Austin, TX 78701",
    company: "Mitchell Properties LLC",
    status: "active",
    totalProjects: 6,
    createdAt: "2024-03-15",
  },
  {
    id: "cust-2",
    name: "James Rodriguez",
    email: "j.rodriguez@citybuild.com",
    phone: "(555) 345-6789",
    address: "890 Commerce Blvd, Dallas, TX 75201",
    company: "CityBuild Development",
    status: "active",
    totalProjects: 3,
    createdAt: "2024-06-22",
  },
  {
    id: "cust-3",
    name: "Emily Chen",
    email: "emily@chenhomes.com",
    phone: "(555) 456-7890",
    address: "567 Maple Ave, Houston, TX 77002",
    company: "Chen Custom Homes",
    status: "lead",
    totalProjects: 0,
    createdAt: "2025-01-10",
  },
  {
    id: "cust-4",
    name: "Robert Williams",
    email: "rwilliams@williamsconstruction.com",
    phone: "(555) 567-8901",
    address: "234 Industrial Pkwy, San Antonio, TX 78205",
    company: "Williams Construction Co.",
    status: "active",
    totalProjects: 12,
    createdAt: "2023-11-08",
  },
  {
    id: "cust-5",
    name: "Lisa Thompson",
    email: "lisa.t@thompsonrealty.com",
    phone: "(555) 678-9012",
    address: "789 Pine Road, Fort Worth, TX 76102",
    company: "Thompson Realty Group",
    status: "inactive",
    totalProjects: 2,
    createdAt: "2024-01-30",
  },
];

export const quotes: Quote[] = [
  {
    id: "quote-1",
    quoteNumber: "QT-2025-001",
    customerId: "cust-1",
    customerName: "Mitchell Properties LLC",
    title: "Kitchen & Bath Remodel",
    description: "Full kitchen renovation with custom cabinetry and master bath update",
    amount: 78500,
    status: "accepted",
    validUntil: "2025-03-15",
    createdAt: "2025-01-20",
  },
  {
    id: "quote-2",
    quoteNumber: "QT-2025-002",
    customerId: "cust-2",
    customerName: "CityBuild Development",
    title: "Commercial Office Build-Out",
    description: "12,000 sq ft office space build-out with HVAC and electrical",
    amount: 245000,
    status: "sent",
    validUntil: "2025-04-01",
    createdAt: "2025-02-01",
  },
  {
    id: "quote-3",
    quoteNumber: "QT-2025-003",
    customerId: "cust-3",
    customerName: "Chen Custom Homes",
    title: "Custom Home Foundation",
    description: "Foundation and slab work for 3,500 sq ft custom residence",
    amount: 52000,
    status: "draft",
    validUntil: "2025-03-30",
    createdAt: "2025-02-05",
  },
  {
    id: "quote-4",
    quoteNumber: "QT-2025-004",
    customerId: "cust-4",
    customerName: "Williams Construction Co.",
    title: "Warehouse Expansion",
    description: "5,000 sq ft warehouse addition with loading dock",
    amount: 189000,
    status: "sent",
    validUntil: "2025-03-20",
    createdAt: "2025-01-28",
  },
];

export const invoices: Invoice[] = [
  {
    id: "inv-1",
    invoiceNumber: "INV-2025-001",
    customerId: "cust-1",
    customerName: "Mitchell Properties LLC",
    quoteId: "quote-1",
    amount: 39250,
    paidAmount: 39250,
    status: "paid",
    dueDate: "2025-02-15",
    createdAt: "2025-01-25",
  },
  {
    id: "inv-2",
    invoiceNumber: "INV-2025-002",
    customerId: "cust-1",
    customerName: "Mitchell Properties LLC",
    quoteId: "quote-1",
    amount: 39250,
    paidAmount: 0,
    status: "sent",
    dueDate: "2025-03-15",
    createdAt: "2025-02-10",
  },
  {
    id: "inv-3",
    invoiceNumber: "INV-2025-003",
    customerId: "cust-4",
    customerName: "Williams Construction Co.",
    amount: 45000,
    paidAmount: 0,
    status: "overdue",
    dueDate: "2025-01-30",
    createdAt: "2025-01-05",
  },
  {
    id: "inv-4",
    invoiceNumber: "INV-2025-004",
    customerId: "cust-2",
    customerName: "CityBuild Development",
    amount: 61250,
    paidAmount: 61250,
    status: "paid",
    dueDate: "2025-02-01",
    createdAt: "2025-01-15",
  },
];

export const employees: Employee[] = [
  {
    id: "emp-1",
    firstName: "Mike",
    lastName: "Johnson",
    trade: "Project Manager",
    mobilePhone: "(555) 111-2222",
    email: "mike.j@constructionos.com",
    truckNumber: "T-101",
    status: "active",
    notes: "Lead PM for commercial projects.",
    department: "Operations",
    hireDate: "2022-04-15",
    hourlyRate: 45,
  },
  {
    id: "emp-2",
    firstName: "Carlos",
    lastName: "Martinez",
    trade: "Lead Carpenter",
    mobilePhone: "(555) 222-3333",
    email: "carlos.m@constructionos.com",
    truckNumber: "T-204",
    status: "active",
    department: "Field",
    hireDate: "2021-08-20",
    hourlyRate: 38,
  },
  {
    id: "emp-3",
    firstName: "Jennifer",
    lastName: "Lee",
    trade: "Electrician",
    mobilePhone: "(555) 333-4444",
    email: "jennifer.l@constructionos.com",
    truckNumber: "T-118",
    status: "active",
    department: "Field",
    hireDate: "2023-01-10",
    hourlyRate: 42,
  },
  {
    id: "emp-4",
    firstName: "David",
    lastName: "Brown",
    trade: "Site Supervisor",
    mobilePhone: "(555) 444-5555",
    email: "david.b@constructionos.com",
    truckNumber: "T-087",
    status: "vacation",
    department: "Operations",
    hireDate: "2020-06-01",
    hourlyRate: 48,
  },
  {
    id: "emp-5",
    firstName: "Amanda",
    lastName: "Foster",
    trade: "Estimator",
    mobilePhone: "(555) 555-6666",
    email: "amanda.f@constructionos.com",
    truckNumber: "T-033",
    status: "active",
    department: "Office",
    hireDate: "2023-09-05",
    hourlyRate: 40,
  },
  {
    id: "emp-6",
    firstName: "Tom",
    lastName: "Reyes",
    trade: "Plumber",
    mobilePhone: "(555) 666-7777",
    email: "tom.r@constructionos.com",
    truckNumber: "T-156",
    status: "sick",
    department: "Field",
    hireDate: "2022-11-12",
    hourlyRate: 41,
  },
];

export const scheduleEvents: ScheduleEvent[] = [
  {
    id: "evt-1",
    title: "Kitchen Demo - Mitchell Properties",
    description: "Begin demolition of existing kitchen",
    start: "2025-02-10T08:00:00",
    end: "2025-02-10T17:00:00",
    customerId: "cust-1",
    customerName: "Mitchell Properties LLC",
    customerPhone: "(555) 234-5678",
    customerEmail: "sarah@mitchellproperties.com",
    billingAddress: "1420 Oak Street, Austin, TX 78701",
    jobSiteAddress: "1420 Oak Street, Austin, TX 78701",
    employeeIds: ["emp-1", "emp-2"],
    employeeNames: [getEmployeeFullName(employees[0]), getEmployeeFullName(employees[1])],
    location: "1420 Oak Street, Austin, TX 78701",
    internalNotes: "Client requested work start before 8 AM.",
    status: "completed",
    type: "job",
  },
  {
    id: "evt-2",
    title: "Electrical Rough-In",
    description: "Electrical rough-in for office build-out",
    start: "2025-02-12T07:00:00",
    end: "2025-02-12T16:00:00",
    customerId: "cust-2",
    customerName: "CityBuild Development",
    customerPhone: "(555) 345-6789",
    customerEmail: "j.rodriguez@citybuild.com",
    billingAddress: "890 Commerce Blvd, Dallas, TX 75201",
    jobSiteAddress: "890 Commerce Blvd, Dallas, TX 75201",
    employeeIds: ["emp-3"],
    employeeNames: [getEmployeeFullName(employees[2])],
    location: "890 Commerce Blvd, Dallas, TX 75201",
    internalNotes: "Coordinate with HVAC crew on site.",
    status: "scheduled",
    type: "job",
  },
  {
    id: "evt-3",
    title: "Site Inspection - Warehouse",
    description: "Pre-construction site inspection",
    start: "2025-02-14T10:00:00",
    end: "2025-02-14T12:00:00",
    customerId: "cust-4",
    customerName: "Williams Construction Co.",
    customerPhone: "(555) 567-8901",
    customerEmail: "rwilliams@williamsconstruction.com",
    billingAddress: "234 Industrial Pkwy, San Antonio, TX 78205",
    jobSiteAddress: "234 Industrial Pkwy, San Antonio, TX 78205",
    employeeIds: ["emp-1", "emp-4"],
    employeeNames: [getEmployeeFullName(employees[0]), getEmployeeFullName(employees[3])],
    location: "234 Industrial Pkwy, San Antonio, TX 78205",
    status: "scheduled",
    type: "inspection",
  },
  {
    id: "evt-4",
    title: "Client Meeting - Chen Homes",
    description: "Review foundation quote and timeline",
    start: "2025-02-15T14:00:00",
    end: "2025-02-15T15:30:00",
    customerId: "cust-3",
    customerName: "Chen Custom Homes",
    customerPhone: "(555) 456-7890",
    customerEmail: "emily@chenhomes.com",
    billingAddress: "567 Maple Ave, Houston, TX 77002",
    jobSiteAddress: "567 Maple Ave, Houston, TX 77002",
    employeeIds: ["emp-5"],
    employeeNames: [getEmployeeFullName(employees[4])],
    location: "Office - Conference Room A",
    status: "scheduled",
    type: "meeting",
  },
  {
    id: "evt-5",
    title: "Cabinet Installation",
    description: "Install custom kitchen cabinets",
    start: "2025-02-17T08:00:00",
    end: "2025-02-17T17:00:00",
    customerId: "cust-1",
    customerName: "Mitchell Properties LLC",
    customerPhone: "(555) 234-5678",
    customerEmail: "sarah@mitchellproperties.com",
    billingAddress: "1420 Oak Street, Austin, TX 78701",
    jobSiteAddress: "1420 Oak Street, Austin, TX 78701",
    employeeIds: ["emp-2"],
    employeeNames: [getEmployeeFullName(employees[1])],
    location: "1420 Oak Street, Austin, TX 78701",
    status: "scheduled",
    type: "job",
  },
  {
    id: "evt-6",
    title: "Roof Repair Estimate",
    description: "Unassigned emergency roof patch — awaiting crew dispatch",
    start: "2025-02-12T13:00:00",
    end: "2025-02-12T15:00:00",
    customerId: "cust-5",
    customerName: "Thompson Realty Group",
    customerPhone: "(555) 678-9012",
    customerEmail: "lisa.t@thompsonrealty.com",
    billingAddress: "789 Pine Road, Fort Worth, TX 76102",
    jobSiteAddress: "789 Pine Road, Fort Worth, TX 76102",
    employeeIds: [],
    employeeNames: [],
    location: "789 Pine Road, Fort Worth, TX 76102",
    internalNotes: "Needs assignment today.",
    status: "scheduled",
    type: "job",
  },
];

export const payments: Payment[] = [
  {
    id: "pay-1",
    invoiceId: "inv-1",
    invoiceNumber: "INV-2025-001",
    customerName: "Mitchell Properties LLC",
    amount: 39250,
    method: "card",
    status: "completed",
    stripePaymentId: "pi_3Qexample001",
    createdAt: "2025-02-01",
  },
  {
    id: "pay-2",
    invoiceId: "inv-4",
    invoiceNumber: "INV-2025-004",
    customerName: "CityBuild Development",
    amount: 61250,
    method: "ach",
    status: "completed",
    stripePaymentId: "pi_3Qexample002",
    createdAt: "2025-01-28",
  },
  {
    id: "pay-3",
    invoiceId: "inv-2",
    invoiceNumber: "INV-2025-002",
    customerName: "Mitchell Properties LLC",
    amount: 39250,
    method: "card",
    status: "pending",
    createdAt: "2025-02-08",
  },
];

export const demoUsers = [
  {
    id: "user-1",
    name: "Admin User",
    email: "admin@constructionos.com",
    role: "admin" as const,
    companyId: "company-1",
  },
];
