import { seed, nettoyer, ouvrir, db, BASE, fermerDialogues } from "./.bug-base.mjs";
const ctx = await seed();
const { nav, page } = await ouvrir(ctx);
await db.from("customers").insert({ company_id:ctx.companyId, name:"Alpha Construction" });
await db.from("quotes").insert({ company_id:ctx.companyId, title:"Format", customer_name:"Alpha", amount:5000, status:"draft", quote_number:"Q-1" });
const d = () => page.locator('[role="dialog"]').last();
await page.goto(BASE+"/schedule",{waitUntil:"networkidle"});
await page.getByRole("button",{name:/Nouveau travail/i}).click(); await page.waitForTimeout(1600);
const t = await d().innerText();
const anglais = t.split("\n").map(x=>x.trim()).filter(x=>/^(Job|Work|Start|End|Billing|Internal|Select|Create|Choose|Phone|Email|Existing|New Customer|Save)/.test(x));
console.log("libellés anglais restants :", anglais.length ? anglais.join(" | ") : "aucun ✓");
await d().locator("#title").fill("Essai");
await d().locator("#date").fill(new Date().toLocaleDateString("en-CA",{timeZone:"America/Toronto"}));
await d().locator("#startTime").fill("16:00"); await d().locator("#endTime").fill("08:00");
await d().getByRole("button",{name:/Créer le travail/}).click(); await page.waitForTimeout(2000);
console.log("message d'erreur :", (await d().innerText()).split("\n").map(x=>x.trim()).find(x=>/heure|client/i.test(x)&&x.length<90) ?? "(aucun)");
await fermerDialogues(page);
await page.goto(BASE+"/schedule",{waitUntil:"networkidle"}); await page.waitForTimeout(1500);
const cal = await page.locator("main").innerText();
console.log("en-tête calendrier :", cal.split("\n").map(x=>x.trim()).find(x=>/Semaine du|^\w+ \d+ \w+ \d{4}/.test(x)) ?? "?");
console.log("jours :", (cal.match(/\b(lun|mar|mer|jeu|ven|sam|dim)\.? ?\d+/gi)||[]).slice(0,4).join(" · ") || "(toujours en anglais)");
await page.goto(BASE+"/quotes",{waitUntil:"networkidle"}); await page.waitForTimeout(1500);
const q = await page.locator("main").innerText();
console.log("montant affiché :", q.match(/[\d  ]+,\d{2}\s*\$|\$[\d,]+\.\d{2}/)?.[0] ?? "?");
await nav.close(); await nettoyer(ctx);
